// SPDX-FileCopyrightText: Iridesium
// SPDX-License-Identifier: GPL-3.0-only

//! The engine-driven mod lifecycle.
//!
//! Charter rule 9's sequence, in one place:
//!
//! ```text
//! scan → resolve → load each in order → CLOSE the registration window →
//! FREEZE → world load → play
//! ```
//!
//! The ordering is not stylistic. Registration order decides numeric material
//! ids, numeric ids go into every chunk blob (charter rule 8), and the world
//! database reconciles against them on open (Task 03). A lifecycle that loaded
//! mods in a different order would hand the same world different ids and
//! reinterpret every block in it.
//!
//! After [`ModHost::freeze`] the registries are immutable and `register_*` is a
//! hard error from Lua. That is what makes the id table safe to persist.

use std::path::Path;

use crate::chunk::Chunk;
use crate::coords::ChunkPos;
use crate::material::MaterialId;
use crate::modload::{ModManifest, ResolvedSet, resolve, scan_directory};
use crate::script::vm::{ScriptError, ScriptVm, VmLimits};

/// Something went wrong bringing mods up.
#[derive(Debug, thiserror::Error)]
pub enum HostError {
    /// A mod directory could not be scanned or a manifest was invalid.
    ///
    /// Boxed: a `ManifestError` carries a `toml` parse error, which is large
    /// enough that every `Result` on the startup path would pay for it.
    #[error("could not read mods from `{root}`")]
    Scan {
        /// The directory scanned.
        root: String,
        /// Why.
        #[source]
        source: Box<crate::modload::ManifestError>,
    },

    /// Dependencies could not be resolved.
    #[error("could not resolve mod dependencies")]
    Resolve(#[from] Box<crate::modload::ResolveError>),

    /// A mod's entry script could not be read.
    #[error("could not read `{path}`")]
    ReadEntry {
        /// The path.
        path: String,
        /// Why.
        #[source]
        source: std::io::Error,
    },

    /// The script VM failed.
    #[error(transparent)]
    Script(#[from] ScriptError),
}

/// Which lifecycle phase the host is in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Phase {
    /// Mods are loading; `register_*` is permitted.
    Registration,
    /// Registries are immutable; generation may run.
    Frozen,
}

/// Owns the mod set and the VM running it.
pub struct ModHost<V: ScriptVm> {
    vm: V,
    resolved: ResolvedSet,
    phase: Phase,
    /// Mods that failed to load. They are skipped, not fatal.
    failed: Vec<(String, ScriptError)>,
    /// What every loaded mod's world options resolved to. See
    /// [`Self::world_options`].
    world_options: Vec<(String, crate::modload::WorldOptionValue)>,
}

impl<V: ScriptVm> ModHost<V> {
    /// Scans a directory, resolves it, and loads every mod in order.
    ///
    /// A mod whose script **fails to load is disabled, not fatal** (charter
    /// rule 10): the rest of the set still comes up, and the failure is
    /// recorded in [`Self::failed`]. A mod set that fails to *resolve* is fatal,
    /// because there is no correct subset to fall back to.
    ///
    /// # Errors
    ///
    /// [`HostError`] if scanning, resolution, or VM creation fails.
    pub fn load_from(root: &Path, limits: VmLimits) -> Result<Self, HostError> {
        Self::load_selected(root, limits, None)
    }

    /// The same, with only the mods in `only` loaded.
    ///
    /// **A selection, not a different loader.** A player turning a mod off in
    /// the launcher is choosing a mod SET, and every rule about that set still
    /// applies: it is resolved, ordered and frozen exactly as a full directory
    /// is. Turning off something another enabled mod depends on is a
    /// resolution failure and is fatal, which is right — there is no correct
    /// subset to fall back to, and the alternative is a world generated by
    /// half a mod set.
    ///
    /// `None` loads everything, which is what a server with no launcher does.
    ///
    /// # Errors
    ///
    /// [`HostError`] if scanning, resolution, or VM creation fails.
    pub fn load_selected(
        root: &Path,
        limits: VmLimits,
        only: Option<&[String]>,
    ) -> Result<Self, HostError> {
        Self::load_selected_with_options(root, limits, only, &[])
    }

    /// The same, for a world that chose these world options.
    ///
    /// `chosen` is what the world file holds — `(qualified id, value text)` —
    /// or what the screen chose for a world that does not exist yet. Each
    /// enabled mod's declarations (`[[world_option]]` in its manifest) are
    /// resolved against it here, so an option no world chose answers its
    /// declared default and a value a renamed option no longer has falls back
    /// to it too. **Installed before any `init.lua` runs**, because a mod may
    /// register differently for one world than for another, and a worker VM
    /// loaded with the same `chosen` resolves to exactly the same list.
    ///
    /// # Errors
    ///
    /// [`HostError`] if scanning, resolution, or VM creation fails.
    pub fn load_selected_with_options(
        root: &Path,
        limits: VmLimits,
        only: Option<&[String]>,
        chosen: &[(String, String)],
    ) -> Result<Self, HostError> {
        let mut discovered = scan_directory(root).map_err(|source| HostError::Scan {
            root: root.display().to_string(),
            source: Box::new(source),
        })?;
        if let Some(only) = only {
            discovered.retain(|found| only.contains(&found.manifest.id));
        }
        let resolved = resolve(&discovered).map_err(Box::new)?;
        for aside in &resolved.aside {
            tracing::info!(
                reference = %aside.reference,
                replaced_by = %aside.replaced_by,
                "a reference mod stood aside for the mod that replaces it"
            );
        }

        // Resolved in LOAD ORDER, so the list is the same on every VM that
        // loads this set — a worker and the tick must agree on it as they do
        // on material ids.
        let mut world_options = Vec::new();
        for entry in &resolved.order {
            let Some(found) = discovered
                .iter()
                .find(|found| found.manifest.id == entry.id)
            else {
                continue;
            };
            for option in &found.manifest.world_options {
                let id = option.qualified(&entry.id);
                let stored = chosen
                    .iter()
                    .find(|(name, _)| *name == id)
                    .map(|(_, value)| value.as_str());
                world_options.push((id, option.resolve(stored)));
            }
        }

        let mut vm = V::create(limits)?;
        vm.set_world_options(&world_options);
        let mut failed = Vec::new();

        for entry in &resolved.order {
            let path = entry.dir.join(crate::modload::manifest_entry_file());
            let source = std::fs::read_to_string(&path).map_err(|source| HostError::ReadEntry {
                path: path.display().to_string(),
                source,
            })?;

            // What this mod may read from — see `game.exports`.
            vm.note_reference(&entry.id, entry.reference);
            vm.note_dependencies(&entry.id, &entry.after);
            if let Err(err) = vm.load_mod(&entry.id, &source, &entry.dir) {
                tracing::error!(
                    mod_id = %entry.id,
                    error = %err,
                    "mod failed to load and is disabled; the rest of the set continues"
                );
                vm.mark_faulted(&entry.id);
                failed.push((entry.id.clone(), err));
            }
        }

        Ok(Self {
            vm,
            resolved,
            phase: Phase::Registration,
            failed,
            world_options,
        })
    }

    /// What this world's mods' world options resolved to, in load order.
    ///
    /// Qualified ids and values — every option every loaded mod declares, with
    /// the world's choice or the declared default. This is what a worker VM is
    /// handed, and what a server persists for a world that has just been made.
    #[must_use]
    pub fn world_options(&self) -> &[(String, crate::modload::WorldOptionValue)] {
        &self.world_options
    }

    /// The theme the engine's own screens should wear, and the mod that set it.
    ///
    /// # Last in load order, and only one
    ///
    /// Two mods blending their idea of a frame is not a look, it is an
    /// accident — so one theme applies and it is the last one declared, which
    /// is the rule a place's fog and tint already follow. Load order is topo
    /// order, so a mod that depends on another paints over it, which is what
    /// "depends on" ought to mean for a look.
    ///
    /// **A mod that failed to load does not get to theme anything.** Its Lua
    /// never ran, none of its blocks or sounds exist, and a client wearing its
    /// frame around screens listing none of its content would be the engine
    /// advertising a mod that is not there.
    #[must_use]
    pub fn theme(&self) -> Option<(&str, &crate::modload::Theme)> {
        let failed: std::collections::BTreeSet<&str> =
            self.failed.iter().map(|(id, _)| id.as_str()).collect();
        self.resolved
            .order
            .iter()
            .filter(|entry| !failed.contains(entry.id.as_str()))
            .rev()
            .find_map(|entry| entry.theme.as_ref().map(|theme| (entry.id.as_str(), theme)))
    }

    /// Closes the registration window.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if the VM cannot be updated.
    pub fn freeze(&mut self) -> Result<(), ScriptError> {
        self.vm.freeze()?;
        self.phase = Phase::Frozen;
        Ok(())
    }

    /// The current lifecycle phase.
    #[must_use]
    pub const fn phase(&self) -> Phase {
        self.phase
    }

    /// The resolved mod set, in load order.
    #[must_use]
    pub const fn resolved(&self) -> &ResolvedSet {
        &self.resolved
    }

    /// Mods that failed to load, with the reason.
    #[must_use]
    pub fn failed(&self) -> &[(String, ScriptError)] {
        &self.failed
    }

    /// Mods currently disabled — failed to load, or faulted at runtime.
    #[must_use]
    pub fn disabled(&self) -> Vec<String> {
        self.vm.faulted_mods()
    }

    /// Generates one chunk by running the registered callbacks.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] naming the mod that failed. That mod is disabled; later
    /// chunks generate without it.
    pub fn generate_chunk(
        &mut self,
        domain: &str,
        world_seed: u64,
        pos: ChunkPos,
        fill: MaterialId,
    ) -> Result<Chunk, ScriptError> {
        self.generate_chunk_with_fluid(domain, world_seed, pos, fill)
            .map(|(chunk, _)| chunk)
    }

    /// The same, keeping any fluid the generator placed.
    ///
    /// **The terrain-only call above is the common one** — a caller asking
    /// what a generator produced almost always means the blocks, and every
    /// test in the workspace does. This is for the one caller that has
    /// somewhere to put an ocean.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if a generator faulted; the mod is disabled and the
    /// chunks generate without it.
    pub fn generate_chunk_with_fluid(
        &mut self,
        domain: &str,
        world_seed: u64,
        pos: ChunkPos,
        fill: MaterialId,
    ) -> Result<(Chunk, crate::fluid::FluidLayer), ScriptError> {
        self.vm.generate_chunk(domain, world_seed, pos, fill)
    }

    /// The biome colour a mod gives one chunk, or white if none does.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if the callback faulted; the mod is disabled and the
    /// chunk is served white.
    pub fn chunk_tint(
        &mut self,
        domain: &str,
        world_seed: u64,
        pos: ChunkPos,
    ) -> Result<[u8; 3], ScriptError> {
        self.vm.chunk_tint(domain, world_seed, pos)
    }

    /// The fog a mod gives one chunk's column, or `None` if none does.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if the callback faulted; the mod is disabled and the
    /// chunk is served without fog.
    pub fn chunk_fog(
        &mut self,
        domain: &str,
        world_seed: u64,
        pos: ChunkPos,
    ) -> Result<Option<crate::proto::ChunkFog>, ScriptError> {
        self.vm.chunk_fog(domain, world_seed, pos)
    }

    /// The VM, for tests and diagnostics.
    pub fn vm_mut(&mut self) -> &mut V {
        &mut self.vm
    }

    /// The VM.
    #[must_use]
    pub const fn vm(&self) -> &V {
        &self.vm
    }
}

/// Reads a mod's manifest without loading it. Diagnostics and `--check-mods`.
///
/// # Errors
///
/// [`crate::modload::ManifestError`] if the manifest is missing or invalid.
pub fn read_manifest(dir: &Path) -> Result<ModManifest, crate::modload::ManifestError> {
    ModManifest::load(dir)
}
